const String baseUrl =
    'https://abubasith86-chat-bot-backend.hf.space'; // For Android emulator, use localhost or 127.0.0.1 for iOS/desktop

const Map<String, String> languageNames = {
  "ar": "Arabic",
  "bg": "Bulgarian",
  "cs": "Czech",
  "da": "Danish",
  "de": "German",
  "el": "Greek",
  "en": "English",
  "es-ES": "Spanish (Spain)",
  "es-US": "Spanish (US)",
  "et": "Estonian",
  "fi": "Finnish",
  "fr": "French",
  "hi": "Hindi",
  "hr": "Croatian",
  "hu": "Hungarian",
  "id": "Indonesian",
  "it": "Italian",
  "ja": "Japanese",
  "ko": "Korean",
  "lt": "Lithuanian",
  "lv": "Latvian",
  "nl": "Dutch",
  "no": "Norwegian",
  "pl": "Polish",
  "pt-BR": "Portuguese (Brazil)",
  "pt-PT": "Portuguese (Portugal)",
  "ro": "Romanian",
  "ru": "Russian",
  "sk": "Slovak",
  "sl": "Slovenian",
  "sv": "Swedish",
  "th": "Thai",
  "tr": "Turkish",
  "uk": "Ukrainian",
  "vi": "Vietnamese",
  "zh-CN": "Chinese (Simplified)",
  "zh-TW": "Chinese (Traditional)",
};
