name: Deploy Flutter Web App

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy-web:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Get full history
          
      - name: Print Commit Info
        run: |
          echo "Building commit: $(git rev-parse HEAD)"
          echo "Commit message: $(git log -1 --pretty=%B)"
          echo "Commit author: $(git log -1 --pretty=%an)"
          echo "Commit date: $(git log -1 --pretty=%ad)"
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.2
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build Flutter Web
        run: |
          flutter config --enable-web
          flutter clean
          flutter pub get
          flutter build web \
            --release \
            --base-href "/${{ github.event.repository.name }}/" \
            --dart-define=FLUTTER_WEB_RENDERER=html \
            --dart-define=FLUTTER_WEB_USE_SKIA=true \
            --no-tree-shake-icons
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
          full_commit_message: "Deploy from: ${{ github.sha }} - ${{ github.event.head_commit.message }}"